
export const SET_CURUSER_INFO = "SET_CURUSER_INFO"
export const QUIT_LOGIN = "QUIT_LOGIN"
export const SET_STUDENT_LIST = "SET_STUDENT_LIST"
export const SET_CONTINUE_DATE = "SET_CONTINUE_DATE"
export const SET_CURRENT_PANEL = "SET_CURRENT_PANEL"
export const SET_MANGECLASS = "SET_MANGECLASS"
export const CHANGR_STUDENT_INFO = "CHANGR_STUDENT_INFO"
