
export const SET_USERNAME = "SET_USERNAME"
export const QUIT_LOGIN = "QUIT_LOGIN"
export const SET_STUDENT_INFO = "SET_STUDENT_INFO"
export const SET_CONTINUE_DATE = "SET_CONTINUE_DATE"
export const SET_CURRENT_PANEL = "SET_CURRENT_PANEL"
export const SET_MANGECLASS = "SET_MANGECLASS"
